###
# \authors   Олег Лесков <oleg@oSvoj.ru>
# \version   0.0.1a
# \date      10.2022
# \copyright MIT
###
PACKAGE=001.osvoj.ru
default: clear
	g++ -o 003.exe ./main.c++

clear:
	rm -rf ./*.exe ./*.o

doc:
	doxygen ./Doxyfile
